config/routes.rb
Mysingers::Application.routes.draw do
  resources :singers

 root 'welcome#index'

end

app/models/singer.rb
class Singer < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/singers_controller.rb
class SingersController < ApplicationController
  before_action :set_singer, only: [:show, :edit, :update, :destroy]

  # GET /singers
  # GET /singers.json
  def index
    @singers = Singer.all
  end

  # GET /singers/1
  # GET /singers/1.json
  def show
  end

  # GET /singers/new
  def new
    @singer = Singer.new
  end

  # GET /singers/1/edit
  def edit
  end

  # POST /singers
  # POST /singers.json
  def create
    @singer = Singer.new(singer_params)

    respond_to do |format|
      if @singer.save
        format.html { redirect_to @singer, notice: 'Singer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @singer }
      else
        format.html { render action: 'new' }
        format.json { render json: @singer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /singers/1
  # PATCH/PUT /singers/1.json
  def update
    respond_to do |format|
      if @singer.update(singer_params)
        format.html { redirect_to @singer, notice: 'Singer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @singer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /singers/1
  # DELETE /singers/1.json
  def destroy
    @singer.destroy
    respond_to do |format|
      format.html { redirect_to singers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_singer
      @singer = Singer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def singer_params
      params.require(:singer).permit(:name, :profile, :picture)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/singers_helper.rb
module SingersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mysingers</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/singers/_form.html.erb
<%= simple_form_for(@singer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :profile %>
    <%= f.input :picture %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/singers/edit.html.erb
<h1>Editing singer</h1>

<%= render 'form' %>

<%= link_to 'Show', @singer %> |
<%= link_to 'Back', singers_path %>

app/views/singers/index.html.erb
<h1>Listing singers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Profile</th>
      <th>Picture</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @singers.each do |singer| %>
      <tr>
        <td><%= singer.name %></td>
        <td><%= singer.profile %></td>
        <td><%= singer.picture %></td>
        <td><%= link_to 'Show', singer %></td>
        <td><%= link_to 'Edit', edit_singer_path(singer) %></td>
        <td><%= link_to 'Destroy', singer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Singer', new_singer_path %>

app/views/singers/new.html.erb
<h1>New singer</h1>

<%= render 'form' %>

<%= link_to 'Back', singers_path %>

app/views/singers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @singer.name %>
</p>

<p>
  <strong>Profile:</strong>
  <%= @singer.profile %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @singer.picture %>
</p>

<%= link_to 'Edit', edit_singer_path(@singer) %> |
<%= link_to 'Back', singers_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>